version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=recipemanager
      - POSTGRES_PASSWORD=recipemanager
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  # server:
  #   build: ./server
  #   command: npm run dev
  #   volumes:
  #     - .:/usr/app/
  #     - /usr/app/node_modules
  #   ports:
  #     - '4000:4000'
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgresql://recipemanager:recipemanager@localhost:5432/recipemanager?schema=public
volumes:
  postgres:
