version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=recipemanager
      - POSTGRES_PASSWORD=recipemanager
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  client:
    command: npm run dev
    tty: true
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - client:/client
      - /client/node_modules
  # server:
  #   command: npm run dev
  #   tty: true
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - 4000:4000
  #   volumes:
  #     - server:/server
  #     - /server/node_modules
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgresql://recipemanager:recipemanager@localhost:5432/recipemanager?schema=public
volumes:
  postgres:
  client:
  server:
