mutation InstructionsUpdateById(
  $id: MongoID!
  $record: UpdateByIdRecipeInput!
) {
  recipeUpdateById(_id: $id, record: $record) {
    record {
      title
      description
      servingSize
      cookTime
      prepTime
      _id
      updatedAt
      createdAt
      instructions {
        description
      }
    }
  }
}
