query recipeById($id: MongoID!) {
  recipeById(_id: $id) {
    title
    description
    cookTime
    prepTime
    servingSize
    instructions {
      title
      description
      stepNumber
    }
    updatedAt
    _id
    createdAt
  }
}
