---
version: "3"

services:
  server:
    image: node:latest
    container_name: server
    restart: always
    working_dir: ./server
    ports:
      - "4000:80"
    depends_on:
      - db
    networks:
      - bridge

  db:
    image: centos/mongodb-36-centos7:latest
    container_name: db
    restart: always
    networks:
      - bridge

networks:
  bridge:
    external: true
    name: bridge
    driver: bridge
