name: Server

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API}}
          heroku_app_name: "pbj-recipemanager-server"
          heroku_email: "info@patrickblackjr.com"
          working-directory: ./server

      
